title: iTip Gmbh
author: Lisa Jonson
email: contact@itip-gmbh.eu

# social links
twitter_username: testcasino
github_username:  1001ideas

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
