title: iTip Gmbh
author: Lisa Jonson
email: contact@itip-gmbh.eu
description: 
We are glad to see you here. Our company has been successful since 2008 and has helped many companies. Contact us and we will be happy to help you too.

# social links
twitter_username: testcasino
github_username:  1001ideas

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
